"""
CRUD operations package.
"""

from app.crud.crud import (
    # Category operations
    get_categories,
    get_category,
    create_category,
    # Menu item operations
    get_menu_items,
    get_menu_item,
    create_menu_item,
    update_menu_item,
    delete_menu_item,
    # Order operations
    generate_order_number,
    get_orders,
    get_orders_paginated,
    get_order,
    get_active_order_for_table,
    create_order,
    update_order,
    admin_edit_order,
    cancel_order,
    update_order_item_served_status,
    update_order_item_served_quantity,
    set_order_item_served_quantity,
    # Payment operations
    create_payment,
    create_payments_batch,
    get_payments_for_order,
    replace_order_payments,
)
from app.crud.crud_analytics import (
    get_revenue_data_tool,
    get_product_data_tool,
    get_order_stats_tool,
    get_inventory_status_tool,
    get_cash_counter_status_tool,
    get_category_performance_tool,
    get_time_comparison_tool,
    get_peak_hours_detailed_tool,
    get_menu_item_details_tool,
    get_payment_method_trends_tool,
    get_product_mix_analysis_tool,
    get_table_performance_tool,
    get_vegetarian_vs_nonveg_tool,
    get_beverage_vs_food_tool,
    get_parcel_vs_dinein_tool,
    get_gst_breakdown_tool,
    get_inventory_usage_trends_tool,
    get_cancellation_analysis_tool,
    get_financial_summary_tool,
    # Helper for analytics
    to_ist_timestamp,
    get_time_filter,
    paise_to_rupees,
    calculate_quartiles,
)

__all__ = [
    # Categories
    "get_categories",
    "get_category",
    "create_category",
    # Menu items
    "get_menu_items",
    "get_menu_item",
    "create_menu_item",
    "update_menu_item",
    "delete_menu_item",
    # Orders
    "generate_order_number",
    "get_orders",
    "get_orders_paginated",
    "get_order",
    "get_active_order_for_table",
    "create_order",
    "update_order",
    "admin_edit_order",
    "cancel_order",
    "update_order_item_served_status",
    "update_order_item_served_quantity",
    "set_order_item_served_quantity",
    # Payments
    "create_payment",
    "create_payments_batch",
    "get_payments_for_order",
    "replace_order_payments",
    # Analytics
    "get_revenue_data_tool",
    "get_product_data_tool",
    "get_order_stats_tool",
    "get_inventory_status_tool",
    "get_cash_counter_status_tool",
    "get_category_performance_tool",
    "get_time_comparison_tool",
    "get_peak_hours_detailed_tool",
    "get_menu_item_details_tool",
    "get_payment_method_trends_tool",
    "get_product_mix_analysis_tool",
    "get_table_performance_tool",
    "get_vegetarian_vs_nonveg_tool",
    "get_beverage_vs_food_tool",
    "get_parcel_vs_dinein_tool",
    "get_gst_breakdown_tool",
    "get_inventory_usage_trends_tool",
    "get_cancellation_analysis_tool",
    "get_financial_summary_tool",
    "to_ist_timestamp",
    "get_time_filter",
    "paise_to_rupees",
    "calculate_quartiles",
]
